controller_manager:
  ros_parameters:
    update_rate: 100 # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros_parameters:
    joints:
      - body_steering_wheel_stir_right
      - body_steering_wheel_stir_left
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity